#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
case "$1" in
  start)
    stat_busy "Starting HTCPCPD"
    pkill -f htcpcpd &> /dev/null
    /usr/bin/htcpcpd -c /etc/htcpcpd.ini &> /dev/null
    add_daemon htcpcpd
    stat_done
    ;;
  stop)
    stat_busy "Stopping HTCPCPD"
	pid=$(cat /var/run/htcpcpd.pid)
	kill $pid
	rm -f /var/run/htcpcpd.pid
    rm_daemon htcpcpd
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
